### ISSUE TITLE
Select option by value/partial text

### ISSUE THREAD

**Issue by lajonat** [sclevine/agouti#100]
Hey,
I have a select element, and I want to select one of the options.
As far as I can see, I can only do this with *Selection.Select, which gets the exact text of the wanted option.

Is there no way to select an option by its value? Or maybe by a partial text?

The problem is that I don't have control over the text of the options, and it might be localized. But the values are a known list.

**Comment by sclevine** [comment]
`*Selection.Select` is a convenience method that `*Selection.Click()`s on options for you
 See: https://github.com/sclevine/agouti/blob/master/selection_actions.go#L142

If you want to click on an option by value or partial text, select that option and click on it.
