### ISSUE TITLE
"Flakiness" in Fill/Clear

### ISSUE THREAD

**Issue by 4ydx** [sclevine/agouti#102]
func (s *Selection) Fill(text string) error

Perhaps this is something being hidden by chromedriver itself, but even when running the latest version on linux, I find that sometimes inputs either wont be filled with the given value or the clear call within fill doesn't succeed and the value is appended to what is already there.  I do not know enough, yet, to really debug this other than to say that it happens.  

A few questions: Is there a debug flag that can help me with this?  How about on the driver level and where would the output be written to?  I will try, of course, to sort this on my own, but if the answers are easy enough, help is appreciated.

**Comment by 4ydx** [comment]
Looking through the client that connects, I don't see anything that would obviously cause this.  It must be flakiness on chromedriver's side.

**Comment by sclevine** [comment]
Good luck! You can pass `agouti.Debug` as an `agouti.Option` when you create an `*agouti.WebDriver`.
