### ISSUE TITLE
Use nil slice instead of empty literal

### ISSUE THREAD

**Issue by jawnsy** [sclevine/agouti#103]
I'd like to propose declaring using nil slices (`var a []string`) instead of an empty literal (`a := []string{}`) where possible, as it avoids an allocation and usually behaves the same in practice.

For example, in https://github.com/sclevine/agouti/blob/master/internal/element/repository.go#L76:

```go
elements := []Element{}
```

looks like it can simply be converted to:

```go
var elements []Element
```

without breaking anything. Dave Cheney talks a bit more about it here: https://groups.google.com/d/msg/golang-nuts/qk_ejaTZ6Yk/NHJWadxBDgAJ

I'm happy to contribute a PR if needed, or you can just close the issue if you disagree, no hard feelings.

Thanks for your work!

**Comment by sclevine** [comment]
Technically, empty slices and `nil` slices **are** different, in that `nil` slices compare equally to `nil`, while empty slices do not. When returning a slice from a method, one might argue that it is better to consistently return either an empty slice or a `nil` slice when the return value is a slice with no elements, in case consumers accidentally rely on a `nil` comparison of the return value. (I forget if this matters for the example you specified -- I wrote that code long ago.)

In other places, we use the more idiomatic `nil` slices. [Example](https://github.com/sclevine/agouti/blob/master/page.go#L261).

(In any case, this is more of stylistic preference than a performance improvement, given that the extra allocation you point out is insignificant compared to communicating with a WebDriver over HTTP.)

**Comment by jawnsy** [comment]
Fair enough! I figure everyone checking array return types ought to be checking `len(a) == 0` rather than `a == nil` but I might be wrong in that assumption...
