### ISSUE TITLE
Take screenshot of webelement

### ISSUE THREAD

**Issue by obonyojimmy** [sclevine/agouti#104]
Id like to propose a function that extends webelements struct and can take screenshot just as the page struct does ... anyone with example please share

**Comment by jadekler** [comment]
`page.Screenshot("/tmp/foo.png")` ?

**Comment by sclevine** [comment]
Apologies for the delay.

This seems very straightforward to implement: https://w3c.github.io/webdriver/webdriver-spec.html#take-element-screenshot

Happy to accept a PR. 

At the `api` package level, you'd want to implement [`GetScreenshot`](https://github.com/sclevine/agouti/blob/master/api/session.go#L151) on `api.Element`.

Then you'd want to expose it at the `agouti` package level, on a `Selection`. It could produce a screenshot for each element selected, or fail if you don't have exactly one element selected.

**Comment by sclevine** [comment]
Closing this in favor of #111.
