### ISSUE TITLE
drag and stop action

### ISSUE THREAD

**Issue by angzhi** [sclevine/agouti#105]
How to perform the drag and stop action on the selected element?
It seems that the function FlickFinger is unable to meet the need, as it releases the mouse automatically when reaches the destination specified by the parameters of offsetX and offsetY.
What I want is to keep the state of click and drag, and release the state only at the time I explicitly call the release function.

**Comment by sclevine** [comment]
Sorry for the delay here.

You can pass an `agouti.HoldClick` to [agouti.Page.Click](https://godoc.org/github.com/sclevine/agouti#Page.Click) to accomplish this.
