### ISSUE TITLE
agouti.saucelabs error in Package

### ISSUE THREAD

**Issue by amalhotragannett** [sclevine/agouti#112]
In the below function the capabilities for Browser should take parameter browser rather than name, so that SauceLabs can access the name as a test file name.

func SauceLabs(name, platform, browser, version, username, accessKey string, options ...Option) (*Page, error) {
	url := fmt.Sprintf("http://%s:%s@ondemand.saucelabs.com/wd/hub", username, accessKey)
	capabilities := NewCapabilities().Browser(name).Platform(platform).Version(version)
	capabilities["name"] = name
	return NewPage(url, append([]Option{Desired(capabilities)}, options...)...)
}

SauceLabs Configuration:
Base config
"platform": "macOS 10.12",
"browserName": "e2e_suite_test:webpage_test:testing-golang",
"version": "58.0",
"acceptSslCerts":true,
"name": "e2e_suite_test:webpage_test:testing-golang"

**Comment by sclevine** [comment]
Resolved in #118.
