### ISSUE TITLE
page.RunScript returns Promise value

### ISSUE THREAD

**Issue by yarikbratashchuk** [sclevine/agouti#114]
Hello)
i wonder if it is possible to get "hello" string from this code:
```
page.RunScript(
     "return new Promise(function(resolve){setTimeout(function(){resolve('hello')}, 3000)});", 
     map[string]interface{}{},
     &res,
)
```
It there a way to wait the promise to resolve?
or maybe you have some other advise for me?

Thanks a lot)

**Comment by yarikbratashchuk** [comment]
maybe i'm doing something wrong?

**Comment by sclevine** [comment]
Sorry for the delay! Two options:
1. Make your script continue executing until it can return the raw data. (This may be difficult in JS.)
2. Have your script set the raw data you care about on the `window` when the promise resolves. Use additional `page.RunScript` calls to monitor the `window` for the value.
