### ISSUE TITLE
Finding selectors on hidden elements...

### ISSUE THREAD

**Issue by smithers1221** [sclevine/agouti#115]
Hi there ... new to a lot of dev stuff, and agouti in particular.  Question on whether I can call Find methods using CSS selectors on elements that are hidden.  

Trying to create a selection object by calling the Find method on a file input field that is hidden.  (Looking to ultimately call the UploadFile method on the selection object, but failing on the step to create the selection object.)

any guidance would be much-appreciated!

**Comment by sclevine** [comment]
Hi @smithers1221, apologies for the delay!

I recommend using `agouti.RunScript` to inject JavaScript into the page to manipulate the hidden input field. It's difficult to interact with hidden elements via the WebDriver, as WebDrivers are designed to replicate user actions (which can't happen on hidden elements).
