### ISSUE TITLE
click and wait

### ISSUE THREAD

**Issue by dlintw** [sclevine/agouti#116]
I'm trying to use agouti to do some browser actions automatically.  Is it possible to remove the following 5 second timeout by wait till timeout(maybe 30 second).
```
myURL := "http://localhost:8080/reports.htm"
page.Navigate(myURL)
time.Sleep(5*time.Second)  
sel := page.FindByLink("xxx")  
t, err := sel.Text()
log.Println(t)
```

**Comment by benwaine** [comment]
Not next to an environment to try this, so treat like sudo code! Something like... 

```go
Expect(page.Navigate("http://localhost:8080/reports.htm")).To(Succeed())
Eventually(page.FindByLink("xxx").Text(), 5).Should(Equal("Text You Are Looking For"))  
```

**Comment by sclevine** [comment]
@dlintw, it's possible to accomplish this by [setting the implicit wait timeout](https://godoc.org/github.com/sclevine/agouti#Page.SetImplicitWait) and selecting based on text. 

That said, I've found that @benwaine's method of retrying requests is more reliable and easier to reason about. You can implement logic to do this yourself (without using Gomega) if you prefer.
