### ISSUE TITLE
DoubleClick not working, it just like a Click()

### ISSUE THREAD

**Issue by dlintw** [sclevine/agouti#117]
I'm trying to run web application automatically.

```
sel = page.FirstByID("myid")
sel.DoubleClick()  // this behavior like Click instead of DoubleClick
```

How to debug it?
Could I use Click to simulate Double Click?

**Comment by sclevine** [comment]
Does `sel.DoubleClick()` return an error? Does it fail to double click in more than one WebDriver? You may be able to call `sel.Click()` twice in quick succession, but I haven't tried this.
