### ISSUE TITLE
Switch between browser tabs

### ISSUE THREAD

**Issue by tite54296** [sclevine/agouti#119]
Is it possible to switch between browser tabs? I tried using SwitchWindow and does not seem to work. I also used WindowCount to validate that the new tab is being recognized as a window but does not seem like it since it is returning 1 instead of 2 which is the number of tabs at the time.

**Comment by sclevine** [comment]
Are you sure that you've successfully opened the new tab? `WindowCount` should pick up new tabs. What webdriver / browser are you using?

**Comment by tite54296** [comment]
Yes, the tab was successfully opened but the WindowCount returns only one window.
