### ISSUE TITLE
Set Browser Width and Height and Browser Type

### ISSUE THREAD

**Issue by stnight** [sclevine/agouti#120]
Is there anyway to achieve this? I'm using PhantomJS as the web driver and I would like to set an options for the headless browser. Based from the godoc there is an Option struct but it didn't explain on how to set some options for the browser,

**Comment by sclevine** [comment]
Hi @stnight,

You can change the window size [using `agouti.Page.Size`](https://godoc.org/github.com/sclevine/agouti#Page.Size). I'm not sure what you mean by "browser type" for PhantomJS.

You may be looking for the `agouti.Desired` option that takes an [`agouti.Capabilities` type](https://godoc.org/github.com/sclevine/agouti#Capabilities), which lets you pass configuration to the WebDriver when the session is created.
