### ISSUE TITLE
How to scroll down? load lazy load images then Screenshot

### ISSUE THREAD

**Issue by ikool-cn** [sclevine/agouti#121]
using PhantomJS.

**Comment by sclevine** [comment]
Here's a [StackOverflow post](https://stackoverflow.com/questions/31963804/how-to-scroll-in-phantomjs-to-trigger-lazy-loads) that covers this. Agouti works the same way as any other library that implements the WebDriver wire protocol.

**Comment by ikool-cn** [comment]
Thanks！
