### ISSUE TITLE
How to click via <li>XXX</li>?And how to find screen point X,Y 

### ISSUE THREAD

**Issue by a7a2** [sclevine/agouti#127]
`<ul class="ui-nav" id="a-loginMethod-tabs">`
  `<li class="" data-status="show_login1">XXX</li>`
  `<li class=" active " data-status="show_login2">login2</li>`
  `<br class="clear" />`
`</ul>`

And how to find screen point X,Y with  `<li>XXX</li>` ?

**Comment by sclevine** [comment]
Have you tried:
```
x, y, err := page.Find("[data-status='show_login1']").Elements()[0].GetLocation()
```
