### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by Bo0mer** [sclevine/agouti#129]
Hello,

Could you please make a new release, since the last one (`2.0`) is somehow old. It is from  Feb 18, 2015 and is 155 commits behind master.

I'm using `dep` to vendor my dependencies, and by default it brings the `2.0` release, which caused some frustration before I was able to realize what was actually happening.

This is what gets in `Gopkg.lock`
```
[[projects]]
  name = "github.com/sclevine/agouti"
  packages = [".","api","api/internal/bus","api/internal/service","internal/element","internal/target","matchers","matchers/internal/colorparser","matchers/internal/page","matchers/internal/selection"]
  revision = "b920a9cc753368454c642011939e1d7ec58e0024"
  version = "v2.0"
```

Thank you for your awesome work!
Cheers,
Ivan

**Comment by sclevine** [comment]
If you're vendoring using `dep` and want the latest v2 release, set the revision to `v2-latest`.

Agouti is always stable on master, and the tags are just used to indicate versions with breaking changes in the API.

I have considered making a `v2` a branch that is even with master, to replace the `v2-latest` tag. If dep has trouble with the `v2-latest` tag, it may like that better. Let me know.

**Comment by Bo0mer** [comment]
3.0.0 is out so I’m closing this.
