### ISSUE TITLE
How to check a page /  No error , no html string?

### ISSUE THREAD

**Issue by marcelloh** [sclevine/agouti#133]
When I use the following code:
```
	err = page.Navigate("http://www.somepagethatreallydoesnotexist.nl")
	if err != nil {
		t.Fatal("Failed to open page:", err)
	}
	fmt.Println("HTML should be a string")
	fmt.Println(page.HTML)
```
I expected the error to be filled, but somehow it isn't.
(I can see that navigate doesn't raise an error, but it's unclear to me why)
ok, then it obviously continue to the printing of the HTM, which according to the documentation should be a string, but the result is:
**0x749970**

How can I check that a page is an existing url, or I get non 200 OK kind of error, and how to get that HTML as a string?

BTW: Just testing it with an existing url (which appears in my chrome) but still, the HTML does not return a string. :-(

**Comment by marcelloh** [comment]
Ok, I got the part where the HTML was not a string. I had to do:
```
fmt.Println(page.HTML())
```
but still, with a non-existing page I get the "ERR_NAME_NOT_RESOLVED"page inside Chrome.

**Comment by sclevine** [comment]
Successfully navigating to a URL with an unregistered domain is different from Agouti failing to navigate to a URL. The current behavior is expected. The WebDriver does not return an error code in this case.

**Comment by marcelloh** [comment]
can you name a situation where Agouti fails to navigate to an url?
(I would say a non existing url seems to fit , but perhaps there's a better explanation in failing)

**Comment by sclevine** [comment]
Any situation where the WebDriver cannot be contacted or returns an error when attempting to navigate.
Common situations might include:
1. Agouti cannot reach the WebDriver
2. The URL is not a valid URL
