### ISSUE TITLE
where is the page.Find tested? (or: examples needed)

### ISSUE THREAD

**Issue by marcelloh** [sclevine/agouti#134]
I only see a lot of tests that are written with the other 2 packages (ginkgo & gomega) but no separate agouti only tests. I was looking for a way to use find, and since the documentation is not that clear about the usage, I thought to look inside the tests, but I don't seem to find it.

I was trying to see if there is a string inside a page:
```
	someVar := page.Find("ERR_NAME_NOT_RESOLVED")
	fmt.Println(someVar)
```
but that didn't do the trick. Find only reacts on selectors.

So basically to check if an URL is a good one, I use this:
```
	someVar := page.Find(".error-code")
	someCount, err := someVar.Count()
	if err == nil {
		if someCount > 0 {
			text, err := someVar.Text()
			if err == nil {
				if strings.Contains(text, "ERR_NAME_NOT_RESOLVED") {
					fmt.Println("URL cannot be found")
				}
			}
		}
	}
```
Isn't there a better way to achieve this?
I think a string compare to find out an url isn't a good one is a bit buggy, so I'm looking for advice here.

**Comment by sclevine** [comment]
The tests you are looking for are [here](https://github.com/sclevine/agouti/tree/master/internal/integration). They are linked to in the [README](https://github.com/sclevine/agouti/blob/master/README.md).

Determining if the page you navigated to belongs to an unregistered domain will vary significantly between WebDrivers and Browsers. I would not recommend using a WebDriver for this task.

The `page.Find()` method only takes CSS selectors. Additional selection methods are [documented](https://godoc.org/github.com/sclevine/agouti).

I recommend indenting your error cases in the code you've provided, instead of indenting the expected flow.

**Comment by sclevine** [comment]
Additionally, there is an example of Agouti used by itself on agouti.org [here](http://agouti.org/#using-agouti-by-itself).

**Comment by marcelloh** [comment]
So I overlooked the:
```
	loginURL, err := page.URL()
	if err != nil {
		panic(err)
	}
```
but this doesn't do it for me either.
isn't there any way in finding out the url isn't a good one?

**Comment by marcelloh** [comment]
The test doesn't show any page.find() that is tested unless you mean you just test the result.
I'm used to testing a functionality by only testing that part (without wrappers to other packages)
so a test of page.Find() would test an empty string, a non-existing string, an 1 time existing string, and a multiple existing string.
Perhaps even (since it should be a selector), every variant of a selector.
But hey, call me careful.
I'm just trying to see what the package can do for me without bothering you, but somehow, I don't understand it's inner workings right now. Glad you help me (or kick me) in the right direction.

**Comment by sclevine** [comment]
The relevant unit tests for the `FindX` methods are here:
https://github.com/sclevine/agouti/blob/master/selectable_test.go
https://github.com/sclevine/agouti/blob/master/api/element_test.go#L50
https://github.com/sclevine/agouti/blob/master/api/session_test.go#L39

Relevant integration tests are here:
https://github.com/sclevine/agouti/blob/master/internal/integration/selection_test.go

Agouti is a fairly thin wrapper on top of the w3c WebDriver spec. It wouldn't make sense for Agouti to exhaustively re-test every combination of selector values, given that the various WebDrivers already contain these type of tests. We do thoroughly test Agouti's interface with the WebDrivers.

I think you're looking for functionality that is already available in the standard library:
https://golang.org/pkg/net/#LookupHost

**Comment by marcelloh** [comment]
Thanks for trying to help me, I fixed the url-not-found in about the same way you mentioned.
