### ISSUE TITLE
how to find a html title tag

### ISSUE THREAD

**Issue by marcelloh** [sclevine/agouti#136]
What I tried:
```
	elm := AgoutiPage.FindByXPath("//title")
	htmltext, _ := elm.Text()
	fmt.Println("title:[" + htmltext + "]")
```
but it gives me nothing
If i show the html via AgoutiPage.HTML(), I see there's a title-tag inside.

I know there's AgoutiPage.Title(), but what if I want to find a &lt; main &gt; tag?
There must be a way to get that (or not)?

**Comment by sclevine** [comment]
I'm not sure if the `<title>` actually has "text" in it, by the webdriver definition of "text." The title contents don't appear as an element on the page.

Can you give me an example of a real page element that doesn't work with `Text()`?

**Comment by marcelloh** [comment]
I think, that text is everything that is: not a tag (or an attribute or an attribute value)

But anyway: , something like this:
```
<main>
   <div class='content'>
      <table><tr>
         <td>table cel 1</td>
         <td>table cel 2</td>
      </tr></table>
   </div>
</main>
```
What I want, is when i do something like elm := AgoutiPage.FindByXPath("//main"),
it will give me all of the above.
(but elm.HTML() is not available there)
When I do elm.Text() I will get only the text out of that (so: "table cel 1 table cel 2")

It would be nice to put this result of elm.HTML() into a AgoutiPage (perhaps this is already possible).
Why:
To have all stuff available on a smaller number of bytes, which must make it quicker (not proven)

Perhaps I need a elm := AgoutiPage.FindByTag("main") :-)
Why?
To test there is a main-tag used on the page (as an example)
(i can do that with elm.Count()

For what my experience now is with Agouti, is that I can only test stuff when it has a CSS element, but perhaps I have too little knowledge in the "how to" :-(

My testsoftware should be able to test everything available that a webserver can throw at me.
(I do that now in another language, but rewriting it in Go)

**Comment by sclevine** [comment]
`FindByName` finds by tag name. Agouti supports all of the WebDriver Spec's Locator strategies.

The WebDriver Spec protocol doesn't support retrieving partial HTML source, only full page source. Agouti cannot implement this until it does.

Agouti is a light-weight wrapper on top of the W3C WebDriver Spec: https://w3c.github.io/webdriver/webdriver-spec.html
If Agouti doesn't have a convenience method for something in that spec, you can call endpoints directly using `page.Session.Send()`.

**Comment by sclevine** [comment]
Closing as resolved.
