### ISSUE TITLE
New version of Chrome opens up chrome://settings/help page when a field is filled.

### ISSUE THREAD

**Issue by rNavarrete** [sclevine/agouti#137]
Running an automated test against the new version of chrome (62) with agouti opens up a new tab with the chrome://settings/help page every time that I fill a field in my test.

![screen shot 2017-10-19 at 3 18 28 pm](https://user-images.githubusercontent.com/3431580/31797048-1482f576-b4e1-11e7-980e-1a275655f287.png)

I manually close the tab while the test runs but any subsequent field that gets filled triggers that page to open in a new tab.

I had to downgrade my chrome version as a workaround.

**Comment by Lacnos** [comment]
Hey

I had the same Problem and just took the newest version of the chrome driver here:https://chromedriver.storage.googleapis.com/index.html?path=2.33/

After that it worked again.

**Comment by sclevine** [comment]
Yep, seems like an issue with that particular version of Chrome. Let me know if you find otherwise. Closing this for now.
