### ISSUE TITLE
Possibility to use a torbrowser

### ISSUE THREAD

**Issue by marcelloh** [sclevine/agouti#140]
I want to test with changing ip adresses via tor.
Is this possible?

I found this for 'simple'  browsing:
https://gist.github.com/Yawning/bac58e08a05fc378a8cc
but not sure in how to use this with Agouti

**Comment by sclevine** [comment]
You would need to configure Agouti to connect to a WebDriver that controls a browser that is configured to use Tor. One way to do this would be to run an HTTP proxy configured to use a tor SOCKS proxy, and provide the HTTP proxy in the `DesiredCapabilities` when connecting:
https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities

**Comment by sclevine** [comment]
Also helpful: https://godoc.org/github.com/sclevine/agouti#ProxyConfig

**Comment by sclevine** [comment]
Closing as resolved. Let me know if you have more questions.
