### ISSUE TITLE
Inject js onLoadStarted

### ISSUE THREAD

**Issue by sulthonzh** [sclevine/agouti#149]
how to inject js onLoadStarted?

i have tried, using page.RunScript but notworking,

need detect window.alert on phantomjs,

**Comment by sclevine** [comment]
PhantomJS does not support certain alert and confirm boxes. Have you tried `page.RunScript` with other webdrivers? Can you provide example code that shows `page.RunScript` behaving incorrectly?

**Comment by sulthonzh** [comment]
ok, thanks @sclevine , i have tried with chrome and working well,

**Comment by sclevine** [comment]
Great to hear :)
