### ISSUE TITLE
Panic with chromedriver >= 2.36

### ISSUE THREAD

**Issue by myitcv** [sclevine/agouti#156]
I'm seeing the following error when using this package with `chromedriver >= 2.36`:

```
panic: failed to retrieve logs: unexpected response: {"sessionId":"2fab477c703c7385add10b6c0e072f29","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.36.540471 (9c759b81a907e70363c6312294d30b6ccccc2752),platform=Linux 4.14.12-041412-generic x86_64)"}}
```

Here is an example build log:

https://travis-ci.org/myitcv/gjbt/builds/359173502

Versions `<= 2.35` are fine.

Thanks

**Comment by sclevine** [comment]
Have you tried 2.37?

This may be due to a change in the logging endpoints. Relevant method is: https://github.com/sclevine/agouti/blob/master/api/session.go#L295

**Comment by myitcv** [comment]
Yes 2.37 failed too (sorry, should have been explicit instead of `>= 2.36`)

**Comment by myitcv** [comment]
Turns out this is actually caused by an issue with Travis's Google Chrome setup: 

https://github.com/travis-ci/travis-ci/issues/9645. 

I now have everything working with Google Chrome `stable` and `beta` for all versions of `chromedriver >= 2.34`:

https://travis-ci.org/myitcv/gjbt/builds/381335012
