### ISSUE TITLE
How can I let Agouti type in some characters

### ISSUE THREAD

**Issue by marcelloh** [sclevine/agouti#157]
I have a screen that reacts to certain charcters, and I want to make a test where this is automated.

I saw something with Click but not sure how to pass a string, or pass a single character.
I also saw SendKeys, but not sure what selection would be.
I have looked for examples, but didn't find usefull stuf :-(

**Comment by sclevine** [comment]
The WebDriver Wire protocol supports two methods for sending keys:
1. `[element]/value` to send keys to an element (same as `selection.SendKeys` in Agouti)
2. `[session]/keys` to send keys to the active element (can use `page.Session().Send("keys", ...)` in Agouti, but not very useful)

Have you tried `page.Find("body").SendKeys`?

**Comment by marcelloh** [comment]
I did the selection.SendKeys, which totally did the trick.
Thanks for guiding me into this :-)
