### ISSUE TITLE
I want `performance`'s LogType

### ISSUE THREAD

**Issue by revenue-hack** [sclevine/agouti#172]
I want performance timing.

agouti version is v3.0.0.

but what returned from `LogTypes` func was

```
2018/10/13 11:58:25 [browser driver]
```

So, Calling `ReadAllLogs` func failed to acquire performance timing.

```
panic: failed to retrieve logs: unexpected response: {"sessionId":"f88e65530af9b1908eead952a8a296e3","status":13,"value":{"message":"unknown error: log type 'performance' not found\n  (Session info: chrome=69.0.3497.100)\n  (Driver info: chromedriver=2.35.528157 (4429ca2590d6988c0745c24c8858745aaaec01ef),platform=Mac OS X 10.13.6 x86_64)"}}
```

Can I get performance logtype in  current situation?

**Comment by sclevine** [comment]
The log types are entirely dependent on the webdriver. There may be capabilities that enable additional log types, but that would be documented by the specific webdriver that you're using.

**Comment by revenue-hack** [comment]
I see.
I will search for a bit, so close this issue.

**Comment by ravsingh96** [comment]
Is there an example of how to add capability of performance logs into chrome driver? I need to see all my redirect links.
