### ISSUE TITLE
Docs about setting up environment for testing

### ISSUE THREAD

**Issue by abourget** [sclevine/agouti#35]
I had a failure running phantomjs.. I'm not sure about the required versions and such. Is there any doc that shows how to setup a testing environment... mostly for integration tests?

Thanks!

**Comment by sclevine** [comment]
Can you post your failure in a gist?

**Comment by sclevine** [comment]
Also, the README.md, the CONTRIBUTING.md, and [agouti.org](http://agouti.org) should provide plenty of information on how to get your environment to run our tests. Try using PhantomJS 1.9.7+

**Comment by abourget** [comment]
ok, was using 1.9.0 .. maybe it's just that.
