### ISSUE TITLE
Report line numbers where `Describe` is.

### ISSUE THREAD

**Issue by abourget** [sclevine/agouti#36]
I'm writing some tests that call several functions, sometimes they are deeply nested, sometimes they aren't.. so calls to `ExpectWithOffset` or `EventuallyWithOffset` can never be certain of the nesting level of the caller.

I was wondering, if we could change the logic of `file:line` reporting to match the file where the `Describe` call is run, and use the line number of the closest function call in that same file.  This way, there are better chances we get the right line number shown.. Or maybe we could have some sort of global switch to change the behavior, on `BeforeSuite` or something ?

What do you think?

**Comment by sclevine** [comment]
This functionality is entirely handled by Ginkgo and is not specific to Agouti. None of `Describe`, `ExpectWithOffset`, `EventuallyWithOffset`, or `BeforeSuite` are provided by Agouti. You could suggest this in [Ginkgo's issues](https://github.com/onsi/ginkgo/issues).

That said, I believe your solution would break globally shared behavior, where, for instance, a `Describe` can call a function that defines an `It`. I might consider passing a call depth counter into methods that eventually call `ExpectWithOffset` and incrementing that counter with each call.

**Comment by abourget** [comment]
ok thanks for the tips :)  I've found some neat ways to use Ginkgo that might resolve the issue I was having.
