### ISSUE TITLE
Running javascript with WebDriver's Execute

### ISSUE THREAD

**Issue by niclupien** [sclevine/agouti#37]
The `page.RunScript` is fine to run inline javascript but the WebDriver's Execute is a must if I want to run heavier javascript like injecting jQuery and other libs.

I already forked agouti to expose `page.Execute` (niclupien/agouti) but I feel there's a reason you didn't exposed it before so I'm opening this issue to start the discussion.

Another alternative would be a new method `InjectScript` that could take the name of file to inject in the page (ex: `page.injectScript("jquery.js")`)

**Comment by sclevine** [comment]
Hi @niclupien, thanks for opening an issue!

Without any arguments, `page.RunScript` just wraps whatever JavaScript you provide it with in a closure. This is generally a safe thing to do with arbitrary JavaScript. Unless your script uses the `var` keyword to declare a variable in the global scope and then expects JavaScript outside of the script to be able to access that variable, there should be no difference. For instance, you should be able to include jQuery with:

```go
script, _ := ioutil.ReadFile("jQuery.js")
page.RunScript(string(script), nil, nil)
```

It's definitely possible that I've missed something. Does this not work like I expect it to?

**Comment by sclevine** [comment]
@niclupien Did this work for you, or am I missing something?

**Comment by sclevine** [comment]
Hi @niclupien, I'd like to close this issue if I answered your question. Are you still having trouble importing scripts?

**Comment by niclupien** [comment]
I've switched on another project for now, your solution looks good, I'll
try it when I get back to it. This issue can be closed.

**Comment by sclevine** [comment]
Thanks! Feel free to re-open this if you run into any issues.
