### ISSUE TITLE
Server starts, but tests don't run (ubuntu 12.04)

### ISSUE THREAD

**Issue by gummybears** [sclevine/agouti#38]
Trying to get Agouti to work on Ubuntu 12.04 
Installed agouti and followed the instructions from the examples.

Tried different combinations of browsers (firefox, google chrome) with Selenium standalone server running on port 4444 and with phantomjs. Not sure which versions I should use for either
Selenium or phantomjs.

No browser is started though, the test just waits. Please advise.
$ go test
running Suite: Test Suite
===============================
Random Seed: 1422079854
Will run 1 of 1 specs

2015/01/24 07:10:55 server started
[negroni] listening on :3000
^C
---------------------------------------------------------
Received interrupt.  Running AfterSuite...
^C again to terminate immediately

Ran 1 of 1 Specs in 5.425 seconds
FAIL! -- 0 Passed | 0 Failed | 0 Pending | 0 Skipped

**Comment by sclevine** [comment]
Hi @gummybears,

Could you link me to some failing code on GitHub, or post your code in a Gist? Your `*_suite_test.go` file and a test file would be extremely helpful.

You need executables for Selenium (`selenium-server`) and PhantomJS (`phantomjs`) in your $PATH for Agouti to find and manage them. You don't need to start either service yourself. This is handled by `core.Selenium` and `core.PhantomJS`, which return `core.WebDriver` objects that you can call `.Start()` on. Agouti is currently tested against Selenium 2.44.0 and PhantomJS 1.9.8. If you have a non-standard WebDriver configuration on your machine, it can easily be accommodated with `core.CustomWebDriver`.

I wish I could be more immediately helpful, but I'll need more information.

**Comment by gummybears** [comment]
I installed both Selenium 2.44.0 and PhantomJS 1.9.8 on Ubuntu, all standard.
Here are the *_suite_test.go files. Basically the files are almost similar to the examples you 
gave, except I test whether the title of the index page matches. Thanks for your help sofar.

Agouti setup 
```
package main_test

import (
  . "github.com/onsi/ginkgo"
  . "github.com/onsi/gomega"
  . "github.com/sclevine/agouti/core"
  "testing"
)

func TestImagetrace(t *testing.T) {
  RegisterFailHandler(Fail)
  RunSpecs(t, "Imagetrace Suite")
}

var agoutiDriver WebDriver

var _ = BeforeSuite(func() {
  var err error

  // Choose a WebDriver:

  //agoutiDriver, err = PhantomJS()
  //agoutiDriver, err = Selenium()
  agoutiDriver, err = Chrome()

  Expect(err).NotTo(HaveOccurred())
  Expect(agoutiDriver.Start()).To(Succeed())
})

var _ = AfterSuite(func() {
  agoutiDriver.Stop()
})
```
My test which just tests if the title is set. 
```
package main_test

import (
  . "bitbucket.org/gummybears/imagetrace"
  . "github.com/onsi/ginkgo"
  . "github.com/onsi/gomega"
  . "github.com/sclevine/agouti/core"
  . "github.com/sclevine/agouti/matchers"
)

var _ = Describe("HomePage", func() {
  var page Page

  BeforeEach(func() {
    var err error

    StartApp()    
    page, err = agoutiDriver.Page()
    Expect(err).NotTo(HaveOccurred())
  })

  AfterEach(func() {
    page.Destroy()
  })
  
  It("navigate to home page",func() {
    By("should display the home page", func() {
      Expect( page.Navigate("http://localhost:3000") ).To(Succeed())   
      Expect( page ).To(HaveURL("http://localhost:3000"))
      Expect( page ).To(HaveTitle("Image Trace") )
    })
  })
})
```

**Comment by sclevine** [comment]
`core.Chrome()` is used to connect directly to ChromeDriver, without Selenium. Change that to `core.Selenium()` and create your page with `agoutiDriver.Page(Use().Browser("chrome"))`.

**Comment by gummybears** [comment]
Made the changes as suggested. Changed chrome to google-chrome, that is the chrome executable on Ubuntu. Got a bit further, when I call go StartApp(), the browser starts, but the test "navigate to home page"  fails with the message
```
failed to open session: failed to retrieve a session ID
```
I am using gorilla/sessions to set a flash message. I will do the test without using the session to get Agouti running first, will check with the Gorilla team about how to handle sessions during test.

**Comment by gummybears** [comment]
I need to read http://godoc.org/github.com/sclevine/agouti/core#Selectable 
Found the right selector, the test runs fine. Thanks.
