### ISSUE TITLE
service.Service.Stop() does not work on Windows

### ISSUE THREAD

**Issue by nycmonkey** [sclevine/agouti#39]
I am writing a screen scraper that needs to run on Windows.  **Agouti works very well - thank you!**  I noticed that the webdriver process was not shutting down properly on Windows after my go program exited (though it did on my mac.)  I believe [this is the relevant code](https://github.com/sclevine/agouti/blob/master/core/internal/service/service.go "service.go"):

```go
func (s *Service) Stop() {
	if s.process == nil {
		return
	}
	s.process.Signal(syscall.SIGINT)
	s.process.Wait()
	s.process = nil
}
```

[The docs for os.Process](http://golang.org/pkg/os/#Process) note that *[s]ending Interrupt on Windows is not implemented.*  This is in conflict with [the docs for os.Signal](http://golang.org/pkg/os/#Signal), which state that *[t]he only signal values guaranteed to be present on all systems are Interrupt (send the process an interrupt) and Kill (force the process to exit).*  Nonetheless, SIGINT doesn't seem to work on Windows.

This hacky solution seems to do the trick:

```go
func (s *Service) Stop() {
	if s.process == nil {
		return
	}
	if runtime.GOOS == "windows" {
		s.process.Signal(syscall.SIGKILL)
	} else {
		s.process.Signal(syscall.SIGINT)
	}
	s.process.Wait()
	s.process = nil
}
```

Of course, this requires adding the runtime package to the imports section...

**Comment by sclevine** [comment]
Hi @nycmonkey, thanks for reporting this!
Should be fixed in d7cec9c492f17b190e32249192b728d61159d2a5.
Let me know if it works for you.

**Comment by sclevine** [comment]
@nycmonkey, did this work for you? Can I close this issue?

**Comment by nycmonkey** [comment]
Issue resolved - thank you!
