### ISSUE TITLE
Nil pointer at Eventually Fill

### ISSUE THREAD

**Issue by EtienneBruines** [sclevine/agouti#43]
# Given
```go
Eventually(page.Find("#username").Fill("demo")).Should(Succeed())
```
(This looks almost the same as the demo code at http://agouti.org/#adding-acceptance-tests )

# results in:
```
Full Stack Trace
  /home/etiennebruines/workspaces/go-all/src/github.com/onsi/gomega/internal/asyncassertion/async_assertion.go:30 (0x58f6ce)
        New: if actualType.Kind() == reflect.Func {
  /home/etiennebruines/workspaces/go-all/src/github.com/onsi/gomega/gomega_dsl.go:199 (0x508ac2)
        EventuallyWithOffset: return asyncassertion.New(asyncassertion.AsyncAssertionTypeEventually, actual, globalFailHandler, timeoutInterval, pollingInterval, offset)
  /home/etiennebruines/workspaces/go-all/src/github.com/onsi/gomega/gomega_dsl.go:181 (0x50892f)
        Eventually: return EventuallyWithOffset(0, actual, intervals...)
  /home/etiennebruines/workspaces/go-all/src/git.huperwebs.nl/nu-1-website/client-server/controllers/login_test.go:37 (0x48dfa9)
        func.007: Eventually(page.Find("#username").Fill("demo")).Should(Succeed())
```

# but why?
It's a nil-pointer exception, because `actualType` (async_assertion.go line 30) is `nil`. 
`actualType` is `nil` because `reflect.TypeOf(actualInput)` returns `nil` when `actualInput` is nil.
`actualInput` is the second argument (type `interface{}`) which has the variable name `actual` at the caller at line 199 at gomega_dsl.go. 
Nothing is being done to that variable in `EventuallyWithOffset` and `Eventually`, it's just being passed along. 
At the end, that `actualInput` (or `actual`) variable is the result of 
```go
page.Find("#username").Fill("demo")
```
However, `.Fill` returns an `error` object. This is `nil`...

# Question
I don't really understand any of it (I don't know the gomega/agouti framework). It's identical to the demo code, but results in an error.

## Background info:
```
Go version 1.3.3
Ginkgo version 1.1.0
ChromeDriver 2.14.313457
```

**Comment by EtienneBruines** [comment]
Perhaps it's something I did, but perhaps it is indeed a bug?

I managed to fix this by doing:

## File `async_assertion.go`
### Line 30 becomes:
```go
if actualType != nil && actualType.Kind() == reflect.Func {
```
(added `actualType != nil`)

### Line 65: becomes 
```go
return actualType != nil && actualType.Kind() == reflect.Func && actualType.NumIn() == 0 && actualType.NumOut() > 0
```
(added `actualType != nil`)

**Comment by sclevine** [comment]
Hi @EtienneBruines,

Thanks for opening an issue! The example on agouti.org is indeed incorrect. The `Eventually` Gomega function may only be used directly with zero-argument `*Selection` methods, like so:
```go
Eventually(page.FindByLabel("Gebruikersnaam").Click).Should(Succeed())
```
For other `*Selection` or `*Page` methods, you need to wrap them in a zero-argument function that returns the error, as you suggested:
```go
Eventually(func() error {return page.FindByLabel("Gebruikersnaam").Fill("demo")}).Should(Succeed())
```
This is also why I provided a `matchers` package, as this:
```go
Eventually(page.FindByLabel("Gebruikersnaam").Attribute("name")).Should(Equal("bob"))
```
suffers the same issue, but this:
```go
Eventually(page.FindByLabel("Gebruikersnaam")).Should(HaveAttribute("name", "bob"))
```
is fine.

I'm leaning towards getting rid of the `dsl` package (which does not provide any asynchronous functionality), and adding matchers for all `*Selection` and `*Page` methods. Example:
```go
Eventually(page.FindByLabel("Gebruikersnaam")).Should(BeFilledWith("demo"))
```
Would that be an improvement?

I've updated the `gh-pages` branch to fix the incorrect examples: 87c921fbfb54437c53be4fd19dafe95dce4663ad
Please don't hesitate to open more issues in the future!

-Stephen

**Comment by sclevine** [comment]
After some thought, I realized that
```go
Eventually(page.FindByLabel("Gebruikersnaam")).Should(BeFilledWith("demo"))
```
implies that Agouti should wait for that field to be filled by something else, which is not the intention. What would you think about matchers that start with `Accept`? Some examples:
```go
Eventually(page.FindByButton("click me")).Should(AcceptClick())
Eventually(page.FindByLabel("username")).Should(AcceptFillWith("demo"))
Eventually(page.FindByLabel("pick one")).Should(AcceptSelectWith("some option"))
```
Not totally sure I like it though. Maybe @onsi would have some opinions?

-Stephen

**Comment by sclevine** [comment]
@EtienneBruines, did this answer your question?
Seems like @onsi hasn't had a chance to look at this.

**Comment by onsi** [comment]
Tricksy.

It sounds like there are really two assertions being made here:

```
Eventually(page).Should(HaveElement("#username"))
Expect(page.Find("#username").Fill("demo")).To(Succeed())
```

I know it's more convenient to turn this into a one-liner but I think having a plethora of matchers to support setting things asynchronously may be more confusing than it's worth.

I prefer the explicitness of the two-liner (and it shouldn't be necessary too often?)

**Comment by sclevine** [comment]
This makes the most sense to me. I've updated agouti.org accordingly. I worry a little bit about situations where the appearance of an element does not correlate to an action succeeding, but these are probably edge cases that can be solved be wrapping the action in a function.

@EtienneBruines, to clarify, your use case would look like:
```go
Eventually(page.Find("#username")).Should(BeFound())
Expect(page.Find("#username").Fill("demo")).To(Succeed())
```
I'm closing this issue for now, but feel free to re-open it.
