### ISSUE TITLE
How to wait for JS excution to finish?

### ISSUE THREAD

**Issue by nvcnvn** [sclevine/agouti#49]
Hi guys, I'm using Agouti for testing my application, its work great for almost my need.  
Can I wait for the JS excution to finish after trigger an even before checking something else?  
For example, in my web page:
```javascript
$("#js-btn").click(function(){
  // take a long time to be done, some ajax load etc
  window.location.replace("http://example.com");
})
```
And in my test, currently I do:
```go
Expect(page.Find("#js-btn").Click()).To(Succeed())
time.Sleep(time.Minute)
Expect(page.URL()).To(Equal("http://example.com"))
```
What can I do for avoiding the Sleep line? Its not really work because who know the network speed can be slower!!

**Comment by sclevine** [comment]
Hi @nvcnvn,

You could use `Eventually` with the `HaveURL` matcher, like this:
```go
Expect(page.Find("#js-btn").Click()).To(Succeed())
Eventually(page).Should(HaveURL("http://example.com/"))
```
If it could take longer than one second for the URL to change, you can pass an explicit timeout to `Eventually`:
```go
Expect(page.Find("#js-btn").Click()).To(Succeed())
Eventually(page, "5m").Should(HaveURL("http://example.com/"))
```
This will continuously check the URL for up to 5 minutes.

**Comment by sclevine** [comment]
@nvcnvn Did this answer your question?

**Comment by nvcnvn** [comment]
AH yes!
Thanks you for the hint!
