### ISSUE TITLE
How to get detailed fail log

### ISSUE THREAD

**Issue by raven-chen** [sclevine/agouti#50]
Hi, Thanks for building this great tool, my integration test run on chrome like a charm **in local**.

However, when I'm trying to get agouti run on semaphore -- a CI provider, I'm blocked. 

Keep getting `panic: runtime error: invalid memory address or nil pointer dereference` error. This is my configuration. 

```
func TestMain(m *testing.M) {
	var t *testing.T
	var err error

	driver = agouti.Selenium()
	driver.Start()

	go Start(PORT)

	page, err = driver.NewPage(agouti.Browser("chrome"))
	if err != nil {
		t.Error("Failed to open page.")
	}

	RegisterTestingT(t)
	test := m.Run()

	driver.Stop()
	os.Exit(test)
}
```

the error stack shows it raised from `page, err = driver.NewPage(agouti.Browser("chrome"))`. I have `selenium-server-standalone-2.44.0.jar` and chrome(also tried firefox) installed. Can't figure out where is the problem. How can I get more detailed error information for debug ?

Thanks for reply.

btw. this is the full error stack

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x466286]

goroutine 1 [running]:
_/home/runner/qor/test/integration.TestMain(0xc20802e410)
	/home/runner/qor/test/integration/setup_integration_test.go:35 +0x326
main.main()
	_/home/runner/qor/test/integration/_test/_testmain.go:66 +0x1d1

goroutine 9 [runnable]:
_/home/runner/qor/test/integration.Start(0x2328)
	/home/runner/qor/test/integration/main.go:49
created by _/home/runner/qor/test/integration.TestMain
	/home/runner/qor/test/integration/setup_integration_test.go:31 +0xa1

goroutine 8 [runnable]:
text/template/parse.lexText(0xc20807e180, 0xa6d140)
	/usr/local/go/src/text/template/parse/lex.go:228 +0x37b
text/template/parse.(*lexer).run(0xc20807e180)
	/usr/local/go/src/text/template/parse/lex.go:198 +0x5d
created by text/template/parse.lex
	/usr/local/go/src/text/template/parse/lex.go:191 +0x1ac
exit status 2
FAIL	_/home/runner/qor/test/integration	0.008s
```

**Comment by sclevine** [comment]
Hi @raven-chen,

First, I suspect you would get a more understandable error message if you checked the error returned by `driver.Start()`.

Second, `agouti.Selenium()` only works if you have a script called `selenium-server` in your `$PATH`. To use a custom Selenium JAR file in the current directory, use `agouti.NewWebDriver()` like so:
```go
command := []string{"java", "-jar", "selenium-server-standalone-2.44.0.jar", "-port", "{{.Port}}"}
agouti.NewWebDriver("http://{{.Address}}/wd/hub", command)
```

Check out the godoc for more info:
https://godoc.org/github.com/sclevine/agouti#NewWebDriver

**Comment by raven-chen** [comment]
Hi @sclevine 

I've set `agouti.NewWebDriver()` in local, it works ok too. But still can't get it work on CI. 

I have Xvfb & selenium-standalone-2.44 & chrome 41.0.2272.89 & ChromeDriver 2.14.313457 on CI. keep get below error. I checked the source code, but can't get useful clue :tired_face: 

```
panic: failed to start before timeout

goroutine 1 [running]:
_/home/runner/qor/test/integration.TestMain(0xc20802e410)
	/home/runner/qor/test/integration/setup_integration_test.go:33 +0x153
main.main()
	_/home/runner/qor/test/integration/_test/_testmain.go:66 +0x1d1

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
exit status 2
FAIL	_/home/runner/qor/test/integration	5.323s
```

Then I replaced webdriver with `PhantomJS` since it doesn't rely on Xvfb. Some simple tests can pass on CI. but other tests like operate a complex form(with rich editor and customised selector) keep failing, selectors that works with Selenium no longer work in phantomJS. `ConfirmPopup` doesn't work too. Does this not supported by PhantomJS ? I remember I saw some notices about this in source code, but can't recall the memory now. Not sure if I used phantomJS in wrong way. Could you take a look please ? here's my codes

```
func TestMain(m *testing.M) {
	var t *testing.T
	var err error

	driver = agouti.PhantomJS()
	driverErr := driver.Start()
	if driverErr != nil {
		panic(driverErr)
	}

	go Start(PORT)

	page, err = driver.NewPage()
	if err != nil {
		panic(err)
	}

	err = page.Size(1600, 900)
	if err != nil {
		panic(err)
	}

	RegisterTestingT(t)

	Expect(page.Navigate("http://www.google.com")).To(Succeed()) // this explained below

	test := m.Run()

	driver.Stop()
	os.Exit(test)
}
```

And one weird thing is, I have to `Expect(page.Navigate("http://www.google.com")).To(Succeed())` to make phantomJS work before navigate to my test server address. I tried set page size before test. but it doesn't help. Without this line of code, `page.HTML()` just return a blank html body tag.

**Comment by sclevine** [comment]
Hi @raven-chen,

PhantomJS does not support alert boxes, which is why `page.ConfirmPopup` is failing for you. You could inject JavaScript using `page.RunScript` that sets `window.onAlert` to a handler function. It seems like PhantomJS is also missing other functionality that you need though. You might want to make sure you're using PhantomJS 2.0, as it has some pretty major improvements.

If you choose to stick with Selenium, confirm that you're making the JAR available in the same directory that the test is run from. To see what errors the Selenium might be returning, you can add the `agouti.Debug` option what you call `NewWebDriver`:
```go
command := []string{"java", "-jar", "selenium-server-standalone-2.44.0.jar", "-port", "{{.Port}}"}
driver = agouti.NewWebDriver("http://{{.Address}}/wd/hub", command, agouti.Debug)
```

Alternatively, if you have ChromeDriver available on your CI (and available on `$PATH` as `chromedriver`) you could try `agouti.ChromeDriver()`.

I'm not sure why you would have to navigate to `http://www.google.com` before navigating to your server URL. Perhaps you aren't waiting enough time for the page to load after you navigate?

Hope this helps!
-Stephen

**Comment by raven-chen** [comment]
Hi @sclevine 

Wish you had a nice weekend ! After switch to ChromeDriver. CI starts run now, but tests have popup confirm still have problem(replaced `ConfirmPopup` with `page.Session().AcceptAlert()` not help). I'll see if I can get green CI by other approach.

Thanks for your kindly & helpful support :smile:
