### ISSUE TITLE
`FindByName` is missing

### ISSUE THREAD

**Issue by mattetti** [sclevine/agouti#52]
```func (s *selectable) FindByName(text string) *Selection {} ```

Not a huge deal, but really convenient helper function.

**Comment by sclevine** [comment]
Is this name a tag name, or a `name` attribute?

**Comment by mattetti** [comment]
Name attribute

**Comment by sclevine** [comment]
Added in d9d5fd6e48e84ac8dd1f3a8b8870164039d83018.
