### ISSUE TITLE
Selenium Hub

### ISSUE THREAD

**Issue by ianwalter** [sclevine/agouti#53]
I'm trying to run the generated suite_test but I'm using Selenium Hub in a Docker container. I think I need to use `NewWebDriver` but I can't figure out why I have to pass a command? I already have it running.

**Comment by sclevine** [comment]
Hi @ianwalter, thanks for opening an issue!

`agouti.NewWebDriver` allows you to start a WebDriver process (specified by `command []string`) on a free port that Agouti will manage for you. If you already have a WebDriver running, you can use `agouti.NewPage` to connect to that WebDriver directly.

Let me know if this answers your question,
-Stephen

**Comment by ianwalter** [comment]
Oh ok, but then how would I specify the Selenium Hub URL (i.e. http://192.168.59.103:4444/wd/hub)?

**Comment by sclevine** [comment]
```go
page, err := agouti.NewPage("http://192.168.59.103:4444/wd/hub")
```

**Comment by ianwalter** [comment]
I get:
```
cannot use "http://192.168.59.103:4444/wd/hub" (type string) as type agouti.Option in argument to agoutiDriver.NewPage
```

**Comment by sclevine** [comment]
You want: https://godoc.org/github.com/sclevine/agouti#NewPage
Not: https://godoc.org/github.com/sclevine/agouti#WebDriver.NewPage

**Comment by ianwalter** [comment]
I'm now getting the following error:
```
<*errors.errorString | 0xc20800b3c0>: {
          s: "failed to connect to WebDriver: unexpected end of JSON input",
      }
      failed to connect to WebDriver: unexpected end of JSON input
```

Selenium log:
```
hub_1     | 01:52:38.254 INFO - Got a request to create a new session: Capabilities [{acceptSslCerts=true}]
hub_1     | 01:52:38.254 INFO - Available nodes: [host :http://172.17.0.18:5555]
hub_1     | 01:52:38.254 INFO - Trying to create a new session on node host :http://172.17.0.18:5555
hub_1     | 01:52:38.254 INFO - Trying to create a new session on test slot {seleniumProtocol=Selenium, platform=LINUX, browserName=*firefox, maxInstances=1}
firefox_1 | 18:52:38.267 INFO - Checking Resource aliases
firefox_1 | 18:52:38.270 WARN - POST /selenium-server/driver/session HTTP/1.1
firefox_1 | java.lang.NullPointerException: sessionId should not be null; has this session been started yet?
firefox_1 | 	at org.openqa.selenium.server.FrameGroupCommandQueueSet.getQueueSet(FrameGroupCommandQueueSet.java:220)
firefox_1 | 	at org.openqa.selenium.server.SeleniumDriverResourceHandler.handleBrowserResponse(SeleniumDriverResourceHandler.java:187)
firefox_1 | 	at org.openqa.selenium.server.SeleniumDriverResourceHandler.handle(SeleniumDriverResourceHandler.java:153)
firefox_1 | 	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
firefox_1 | 	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
firefox_1 | 	at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)
firefox_1 | 	at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
firefox_1 | 	at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
firefox_1 | 	at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
firefox_1 | 	at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
firefox_1 | 	at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:358)
firefox_1 | 	at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:537)
```

Not sure if this is due to my set up but seems to work with Capybara.

**Comment by sclevine** [comment]
Hi @ianwalter,

Could you create a gist with some code that replicates this issue? It seems like Selenium is failing to create a session when Agouti POSTs to `/selenium-server/driver/session`. Are you sure `/selenium-server/driver` is the correct webdriver hub URL?

**Comment by stuartaroth** [comment]
Hey @sclevine sorry to be jumping in so late but I'm having the same issue.

I am running a selenium/standalone-chrome instance on 45.55.138.28 currently ( https://github.com/SeleniumHQ/docker-selenium )

In my code I have this basically:

`page, err := agouti.NewPage("http://45.55.138.28:4444/wd/hub")`

And I get the result:

`failed to connect to WebDriver: failed to retrieve a session ID`

I was able to verify that the selenium instance is up by using the example from `github.com/tebeka/selenium` and "http://45.55.138.28:4444/wd/hub", however the api for the package doesn't work nearly as well as agouti.

Here's the actual code I am running: https://github.com/stuartaroth/testy-mctestface/blob/master/testy-mctestface.go

If you pulled the repo and built it using `./build` you would then run `./testy-mctestface example.json` to get the same result I'm getting.

If the reason for this has already been answered elsewhere I'd appreciate a link but I didn't find anything yet.

Thanks for your time!!

**Comment by vsimon** [comment]
Ran into this issue and this solved it https://github.com/sclevine/agouti/issues/69#issuecomment-195559479

**Comment by sclevine** [comment]
Re-opened #69 until this is better documented.
