### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by sclevine** [sclevine/agouti#54]
- Add `Example`s to Godoc
- Document that PhantomJS <=1.9.8 applies page load timeout to non-navigation commands

**Comment by t3hmrman** [comment]
Could you add more guidance around how to use Agouti with TLS-enabled servers? 

I currently get panics like this:
```
015/08/30 15:07:19 http: TLS handshake error from 127.0.0.1:40197: tls: client offered an unsupported, maximum protocol version of 300
```

I've been looking through the source code, and can't find any interface that would let me update the client that agouti is using

**Comment by t3hmrman** [comment]
Could you add some more guidance on how Agouti should be used over TLS connections?

**Comment by sclevine** [comment]
Hi @t3hmrman,

Thanks for pointing this out!

I've been meaning to add support for injecting a custom `http.Client` into a `WebDriver` / direct `Page` connection. Feel free to open an issue about this specifically. I should have time to work on this in the next couple of days. For now, updating `http.DefaultClient` with your TLS settings should let you work around the errors your getting (see `api/internal/bus/client.go`).

**Comment by t3hmrman** [comment]
Thanks a lot - no rush! I was having a hard time figuring out if it was my fault (if I had the server incorrectly configured). Will create another ticket for that, thanks

**Comment by hermanjunge** [comment]
Hi. I wanted to fix-and-PR a little mistake at `agouti.org`, but can find the repository. Do you have plans to make it public in the future?

Replace

````
Eventually(page.FindyByLabel("E-mail")).Should(BeFound())
````

By

````
Eventually(page.FindByLabel("E-mail")).Should(BeFound())
````
Keep up the good work!

**Comment by sclevine** [comment]
Hi @hermanjunge, thanks for catching that!

The website is publicly available under the `gh-pages` branch.

**Comment by hermanjunge** [comment]
Gotcha! Next time I'll send a PR there. Thanks a lot.
