### ISSUE TITLE
Support custom http.Client for use by agouti.Page

### ISSUE THREAD

**Issue by t3hmrman** [sclevine/agouti#57]
It would be nice to offer support for a custom http.Client to be used behind the scenes.

For example, TLS connections fail with the following error:
```
2015/08/30 15:32:25 http: TLS handshake error from 127.0.0.1:38010: tls: client offered an unsupported, maximum protocol version of 300
```

But there is no way to change the Client that is being used currently (and thus no way to fix the error other than making a local edit to agouti).

**Comment by sclevine** [comment]
You can actually work around this by modifying `http.DefaultClient` until I get a chance to address this. No changes to Agouti needed.

**Comment by sclevine** [comment]
Finished by 26c5f50906c9acd82d25ed8fb543f156c7da523b.
This adds an `agouti.HTTPClient` `Option` that can be used when creating a new `WebDriver` or `Page`.

**Comment by t3hmrman** [comment]
Thanks for the hard work! Great library as always, I couldn't imagine
writing end to end tests without it
