### ISSUE TITLE
Loading Chrome extensions

### ISSUE THREAD

**Issue by mattetti** [sclevine/agouti#59]
Hey Steven, I'm trying to find a way to load chrome extensions into the chromedriver so I can run tests with an ad-blocker extension but unfortunately I can't figure out how to.

According to this SO entry: http://stackoverflow.com/questions/16800689/running-webdriver-with-extensions-crx-files I should be able to do something like:

```
chop = webdriver.ChromeOptions()
chop.add_extension('Adblock-Plus_v1.4.1.crx')
driver = webdriver.Chrome(chrome_options = chop)
```

It looks like I might have to use `api.NewWebDriver` and pass the command by hand, but I'm not quite sure.

**Comment by sclevine** [comment]
Hey Matt,

I haven't tried this before, but you should be able to do this with the `agouti.Desired` `Option`.
Try this:
```go
webDriver := agouti.ChromeDriver(agouti.Desired(agouti.Capabilities{
    // NOTE: relying on json.Marshal to convert []byte to base64
    "chromeOptions": map[string][][]byte{ 
        "extensions": {getCRXBytesFromFile()},
    }
}))
...
```
See: https://sites.google.com/a/chromium.org/chromedriver/capabilities

Let me know if this helps!

**Comment by sclevine** [comment]
Hey Matt,

Any luck with this?

**Comment by mattetti** [comment]
We haven't tried yet, the issue is that we are using selenium and open a chrome page, so we need to change our code. Also before starting, what's `getCRXBytesFromFile()`? is that how we are supposed to load the extension file?

**Comment by sclevine** [comment]
Sorry if that wasn't clear:
```
crxBytes, _ := ioutil.ReadFile("/path/to/extension.crx")
webDriver := agouti.ChromeDriver(agouti.Desired(agouti.Capabilities{
    // NOTE: relying on json.Marshal to convert []byte to base64
    "chromeOptions": map[string][][]byte{ 
        "extensions": {crxBytes},
    }
}))
```

**Comment by mattetti** [comment]
Sorry I never commented and closed this issue, I was indeed able to load an extension as per your example. Thank you!
