### ISSUE TITLE
phantomjs loadImages

### ISSUE THREAD

**Issue by torrens** [sclevine/agouti#62]
I'm trying to load a PhantomJS page without loading images to speed thing up.

I've tried the following but it still loads images:

```
capabilities := agouti.NewCapabilities().Without("loadImages")
driver := agouti.PhantomJS(agouti.Desired(capabilities))
```

Can this setting be used?

**Comment by sclevine** [comment]
Sorry for the delayed response.

`--load-images` is a flag to PhantomJS, not a WebDriver capability. You can create a PhantomJS process any way you like with the `agouti.NewWebDriver` function.

Example:
```go
func PhantomJSWithoutImages() *agouti.WebDriver {
	command := []string{"phantomjs", "--webdriver={{.Address}}", "--load-images=false"}
	return agouti.NewWebDriver("http://{{.Address}}", command)
}
```
