### ISSUE TITLE
Expose :sessionid/timeouts

### ISSUE THREAD

**Issue by abourget** [sclevine/agouti#68]
https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidtimeouts reads like there are endpoints to set default timeout values.

Though I don't see anything in `agouti` that handles that.. is that the case ?

If it's so, I propose implementing it on a `Page` obj.

**Comment by sclevine** [comment]
These timeouts are settable via https://godoc.org/github.com/sclevine/agouti/api#Session.SetImplicitWait
which is accessible via `page.Session()`

That said, implementing these timeouts in Go by polling seems to result in less flakey tests.
