### ISSUE TITLE
appium docs

### ISSUE THREAD

**Issue by mattetti** [sclevine/agouti#72]
@abourget @sclevine I'm super excited about the Appium support but getting my test suite up and running is quite painful. So far I'm getting to the point where my webdriver isn't getting a session ID:

```
failed to connect to WebDriver: failed to connect to WebDriver: failed to retrieve a session ID
```

A quick example to get started would be super useful.

Thanks

**Comment by mattetti** [comment]
@abourget @sclevine 

> *polite bump :)*

**Comment by abourget** [comment]
I agree it'd be neat to have docs.. was all of the appium support merged in already ?

As for your error, you can start appium with the debug flags, and/or log stuff to a file, you'll then have a better understanding of what flags you need to pass.

https://github.com/sclevine/agouti/blob/master/appium/webdriver.go#L14-L20

or tweak those lines to add the debug flags to the `appium` call.. Tell me if that helps.

**Comment by mattetti** [comment]
@abourget I believe it's all merged. Here is what I'm doing:

```
options := appium.Desired(agouti.Capabilities{
		"platformName":    platform,
		"platformVersion": platformVersion,
		"app":             buildPath,
		"Debug":           true,
		"Port":            "4723",
	})

	wd := appium.New(options)
	if err := wd.Start(); err != nil {
		t.Fatal(err)
	}
	device, err := wd.NewDevice()
	if err != nil {
		t.Fatal(err)
	}
	if err = wd.Start(); err != nil {
		t.Fatal(err)
	}
```

Am I missing something obvious?

**Comment by abourget** [comment]
Once the driver is started, no need to start it again (second call to
`Start` in there). Is that where it fails ?

Which platform are you on?

What sort of device are you trying to automate ?

From the command line, run `appium --help` directly and find the options to
enable debugging output from the server.

I'm not sure you should specify a Port in the capabilities.. I think agouti
finds a free port and passes it to the driver.

Check these out (and read the source of the `New()`  call.)

Le mar. 26 avr. 2016 14:44, Matt Aimonetti <notifications@github.com> a
écrit :

**Comment by mattetti** [comment]
Sorry it was a bad copy/paste, the error happens on `wd.NewDevice()` in the following code:

```go
var platformVersion string
	var buildPath string
	if platform == Android {
		platformVersion = "6.0"
		// TODO: path to apk
	} else {
		platformVersion = "8.1"
		buildPath = "../builds/MyApp.ipa"
	}
	options := appium.Desired(agouti.Capabilities{
		"platformName":    platform,
		"platformVersion": platformVersion,
		"app":             buildPath,
		"Debug":           true,
	})

	wd := appium.New(options)
	if err := wd.Start(); err != nil {
		t.Fatal(err)
	}
	device, err := wd.NewDevice()
	if err != nil {
		t.Fatal(err)
	}
	return wd, device
```

I'm on OS X, I'm trying to automate iOS and Android using the emulators first. I am not running appium but it is working and it is in my path.

**Comment by mattetti** [comment]
@abourget I'm not quite sure what to try, I feel that I'm missing something super obvious :(

**Comment by abourget** [comment]
Come to #agouti on gophers.slack.com .. perhaps we can try to track this
down.

**Comment by chordabmx** [comment]
@abourget @sclevine Hello guys, first of all thanks for the great library! We are using agouti for Web automation and it works like a charm, so we've decided to use it for mobile automation as well. But unfortunately we've faced with same issue "**failed to connect to WebDriver: failed to connect to WebDriver: failed to retrieve a session ID**", Is there any sort of affordable documentation for appium package or get started example as for agouti?
line causing error is : ```err = device.InstallApp( "./installed-release.apk")```
Code we are trying to run:
```package autotests_mobile

import (
	"fmt"
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
	"github.com/sclevine/agouti"
	."github.com/sclevine/agouti/appium"

	"testing"
)

func TestAndroid(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "Android")
}

var options = Desired(agouti.Capabilities{
"platformName":    "Android",
"platformVersion": "7.0",
"deviceName":      "TECNO SPARK CM",
"Debug":           true,
"automationName": "UiAutomator2",


})
var wd = New(options)


var _ = BeforeSuite(func() {
	err := wd.Start()
	device, err := wd.NewDevice()
	if err != nil {
		fmt.Println(err)
	}
	err = device.InstallApp( "./installed-release.apk")
	err = device.LaunchApp()
	

})

var _ = AfterSuite(func() {
         err = device.CloseApp()
	Expect(wd.Stop()).To(Succeed())
})
```

**Comment by un000** [comment]
Well, so how can I set `http://appiumdocker:4444/wd/hub` as remote?

**Comment by mpermperpisang** [comment]
Hi, all
I try this but get error when InstallApp. this is my code and my error log
Does anybody also get error when install the apps? because when I try manual it is worked and no error

> options := appium.Desired(agouti.Capabilities{
		"platformName":    "Android",
		"platformVersion": "7.1.1",
		"app":             "/Users/bukalapak/Dropbox/APK/app.apk",
		"deviceName":      "MperMperPisang-Xiaomi",
		"udid":            "5857408c",
		"Debug":           true,
		"automationName":  "UiAutomator2",
		"Port":            "4723",
	})

	Driver = appium.New(options)

	if err := Driver.Start(); err != nil {
		log.Fatal(err)
	}

	if _, err := Driver.NewDevice(); err != nil {
		log.Fatal(err)
	}
        
        if err := Device.InstallApp("/⁨Users⁩/bukalapak⁩/⁨Dropbox⁩/⁨APK⁩/app.apk"); err != nil {
		log.Fatal(err)
	}

	if err := Device.LaunchApp(); err != nil {
		log.Fatal(err)
	}

<img width="677" alt="Screen Shot 2019-08-14 at 17 22 13" src="https://user-images.githubusercontent.com/20101521/63014163-15c4f500-beb8-11e9-81cb-51ad1200f718.png">
