### ISSUE TITLE
Wait for selection to load

### ISSUE THREAD

**Issue by mvbaffa** [sclevine/agouti#74]
Hi,

I am new to Agouti. I am using selenium server and chromewebdriver in windows. I have started both and my program is loading Chrome with the first page.

The problem is that I must Find a href element by class name. It works ok, at least the selenium server logs that the element was found. Then I want to click on it to navigate to another page and nothing happens. 

The code is like this, very simple:

if err := page.Navigate("http://www...."); err != nil {
        log.Fatal("Failed to navigate:", err)
    }

```
mainPage, err := page.URL()
if err != nil {
    log.Fatal("Failed to get page URL:", err)
}

expectedLoginURL := "http://www..../home"
if mainPage != expectedLoginURL {
    log.Fatal("Expected URL to be", expectedLoginURL, "but got", mainPage)
}

linkSeries := page.FindByClass("Imprensa")
if err != nil {
    log.Fatal("Failed to get linkSeries :", err)
}

linkSeries .Click()
```

 I have put a break point on the click to wait a few seconds and le the page load. But it does not works.

By the wai how can I wait for an element to load. Selenium has this feature.

Thanks

**Comment by sclevine** [comment]
Hi @mvbaffa,

I use `Eventually` from [Ginkgo](https://onsi.github.io/ginkgo/) for this. Check out the examples at [agouti.org](http://agouti.org). If you don't want to use Ginkgo, you could implement something similar by re-trying the request. I actually find that re-trying requests results in less flakey tests compared to setting the various WebDriver timeouts.

That said, you can set the page load timeout using [`page.Session().SetPageLoad()`](https://github.com/sclevine/agouti/blob/master/api/session.go#L455) to replicate the Selenium behavior.

**Comment by mvbaffa** [comment]
Working with C# and Selenium I have Webdriver wait that I can use to wait for a DOM element to be loaded. In some cases this is important.

I would like to use it with a maximum timeout. Does SetPageLoad defines a fixed timeout or it waits the until the timeout value.

How can I reproduce the Selenium WebDriver and wait for a DOM Element ?

Thanks

**Comment by mvbaffa** [comment]
Just to complete I am working on a Scraper. I am not using agouti for web page test purposes.

Thanks again

**Comment by sclevine** [comment]
You should use `page.Session().SetImplicitWait()` (instead of `SetPageLoad`) if you would like Selenium to wait for a DOM element to exist when you attempt to find it. The [W3C spec](https://w3c.github.io/webdriver/webdriver-spec.html#sessions) explains what the different timeouts are for and how to use them.

That said, I recommend my suggestion from #77 instead.
