### ISSUE TITLE
Load and Close Chrome Silently and driver.Stop crashing

### ISSUE THREAD

**Issue by mvbaffa** [sclevine/agouti#76]
Hi,

I am using Agouti to Scrape a web page. Everything It is working ok except that the chrome window remains opened after the processing is finished.

When I call driver.stop like this:
```
	if err := driver.Stop(); err != nil {
		log.Fatal("Failed to close pages and stop WebDriver:", err)
	}

```
I receive the error message: 

> Failed to close pages and stop WebDriver:failed to stop service: failed to stop command: TerminateProcess: Access is denied.

Why is the stop crashing? 
Is this why the chrome window is not closed at the end ?

By the way I am opening like this:

```
func openSelenium(options ...agouti.Option) *agouti.WebDriver {
	command := []string{"java", "-jar", "<path>\\selenium-server-standalone-2.53.0.jar", "-port", "5555"}
	return agouti.NewWebDriver("http://127.0.0.1:5555/wd/hub", command, options...)
}
```

The Chromedriver is in the path.

Thanks

**Comment by mvbaffa** [comment]
If I call 
`gomega.Expect(page.Destroy()).To(gomega.Succeed())`

The browser is closed correctly. 

But I still do not know how to instantiate Chrome silently.

**Comment by sclevine** [comment]
Does calling `page.Destroy()` before `driver.Stop()` also fix the `TerminateProcess: Access is denied` error? That error indicates that Windows won't let you terminate the WebDriver process for some reason.

What do you mean by "instantiate Chrome silently?" Do you mean headlessly? Is this a separate issue, or is it related to the error?

**Comment by mvbaffa** [comment]
No this is not a separate but an associated issue. I would like to instantiate chrome hidden, that is headlessly as you said and close at the end of the program.

My application will be installed in the users desktop so I would like to scrape the pages in silence, that is I do not want the user to see a popup, or even a minimized, chrome window to appear. At this time When I start my application a chrome window, sometimes, normally opened, other time mimized is displayed.

I can now close the browser window with: 
`gomega.Expect(page.Destroy()).To(gomega.Succeed())`

I need now to start the browser without displaying any window, even minimized.

Can you help me ?

Thanks

**Comment by sclevine** [comment]
On Linux this is possible [via xvfb](https://gist.github.com/alonisser/11192482). On any OS, this is possible by running a headless VM that runs Chrome+Selenium.

Alternatively, you could use PhantomJS instead of Selenium. It works extremely well with Agouti (check out `agouti.PhantomJS()`), and runs (headlessly) on all common OSs.

**Comment by mvbaffa** [comment]
You said "On any OS, this is possible by running a headless VM that runs
Chrome+Selenium"

I will run in Windows, how can I do it?

Thanks

**Comment by sclevine** [comment]
[Here's an example](http://www.chrisle.me/2013/08/running-headless-selenium-with-chrome/), but this solution is very heavy-weight. You probably don't want to require your users to run a VM just to run Selenium. I would strongly recommend PhantomJS for your use case.

**Comment by mvbaffa** [comment]
I see, Maybe PahntomJS is better to work run headless, but do you think the
performance comparable to Selenium ?

I have a lot of pages to scrape, table with a lot of rows. I have tested
PhantomJs with CasperJS and the performance did not seemed to be good.
Working with Agouti+Selenium it seemed to have a better perfvormance.

I could start 5 goroutines and it worked ok.

I can test PhantomJS but I am not sure about its performance.

Thanks

**Comment by sclevine** [comment]
In my experience, PhantomJS is usually faster. I usually use it directly, without Selenium. It has very few dependencies, so it's a convenient dependency for an application that you distribute to users.

**Comment by mvbaffa** [comment]
Ok.

I will try it out.

Thanks

**Comment by mvbaffa** [comment]
Just one more question.

I am using windows, installed PhantomJS and put in the %PATH%.

Now I am trying to start agouti with PhantomJS 

> Failed to start PhantomJS:failed to start service: failed to run command: exec: "phantomjs": executable file not found in %PATH%

I am executing the commands:
```
driver := agouti.PhantomJS()

	if err := driver.Start(); err != nil {
		log.Fatal("Failed to start PhantomJS:", err)
	}
```

But it is in the in %PATH%

Can you help me

**Comment by sclevine** [comment]
Agouti calls `exec.Command()` with `phantomjs` as the command path. If a binary called `phantomjs` is in your OS path, it should work. If you can't get that to work, you could specify a custom command using `agouti.NewWebDriver`. Check out how `agouti.PhantomJS` works: https://github.com/sclevine/agouti/blob/master/agouti.go#L21

**Comment by mvbaffa** [comment]
It was a problem with Intellij. For some reason I had to close and reopen
Intellij and it worked.

Thank you very much.
