### ISSUE TITLE
Customized RegisterFailHandler

### ISSUE THREAD

**Issue by mvbaffa** [sclevine/agouti#77]
Hi,

I need to retry this command if "aaa" is not found in the scraped page:
 
`gomega.Eventually(page.FindByLink("aaa")).Should(matchers.BeFound())`

I have written my own fail handler:

```
func failHandler(message string, callerSkip ...int) {

}
```
What must I do in my own fail handler to retry the command and if successfull return to my execute the rest of my script?

I suppose I must use the parameter callerSkip, but How?

Thanks

**Comment by sclevine** [comment]
What command are you talking about? Do you mean any arbitrary command?

With an adequate timeout,
```
gomega.Eventually(page.FindByLink("aaa")).Should(matchers.BeFound())
```
will block until the element is found, at which point you can run a command that relies on the element.

Example:
```
gomega.Eventually(page.FindByLink("aaa"), "10s").Should(matchers.BeFound())
gomega.Expect(page.FindByLink("aaa").Click()).To(matchers.Succeed())
```

**Comment by mvbaffa** [comment]
I have read more carefully the documentation and I have inserted the exact command you told me. 
`gomega.Eventually(page.FindByLink("aaa"), "10s").Should(matchers.BeFound())`

It is runnig ok but there is a long sequence of commands before and after the Eventually command. If, for some reason, the link is not found and the Eventually times out I would like to restart the whole sequence of commands.

But after my fail handler is called the execution returns to the line just after the Eventually command. How can I stop the sequence and instead of returning to the next line. How can I, from inside the fail handler, notify the function that was running that I would like to stop it.

Thanks

**Comment by sclevine** [comment]
You could `panic` in your fail handler, have your method `recover` from the `panic` and then re-run your method. There a number of possible solutions to this problem.

This seems more like a general Go question -- Agouti is a small library designed to do one thing well: drive a browser using a WebDriver Wire Protocol compliant WebDriver. It plays very nicely with Ginkgo and Gomega for acceptance testing, but outside of that use case, you'll need to implement your own application flow control logic.

**Comment by mvbaffa** [comment]
I am sure I could panic and recover. I was just wondering if there was in
agouti something like an error notification or something like that.

I will try a conventional Go solution. like panic/recover or use a channel.

Thank you very much
