### ISSUE TITLE
PhantomJS userAgent

### ISSUE THREAD

**Issue by sebastianmacias** [sclevine/agouti#80]
Hi there,

Is there a way to set the useragent for the phantomjs driver/page?

Something like: page.settings.userAgent = 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36';

**Comment by Supro** [comment]
Hi, code below should work

```go
capabilities := agouti.NewCapabilities()
capabilities["phantomjs.page.settings.userAgent"] = "'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36';"
capabilitiesOption := agouti.Desired(capabilities)
agoutiDriver = agouti.PhantomJS(capabilitiesOption)
```
