### ISSUE TITLE
Tag v2 for gopkg.in

### ISSUE THREAD

**Issue by wkhere** [sclevine/agouti#84]
Hi!

Can you push a tag like `v2` or `v.2.1` to your stable version so it's retrievable via [gopkg.in](http://gopkg.in/). 
That service doesn't support tags like `v2-latest`.

TIA

**Comment by sclevine** [comment]
Sorry for the delay. I don't think Agouti can work with gopkg.in, because it has import paths that reference subdirectory packages with `github.com/sclevine/agouti/*`.

**Comment by wkhere** [comment]
I see.

My idea of getting 2.0 tag via gopkg.in has appeared because agouti [is already there](https://gopkg.in/sclevine/agouti.v1). Is that entry obsolete then?

**Comment by wkhere** [comment]
Btw agouti is really cool, thanks for creating it!

**Comment by sclevine** [comment]
I'm happy that you find it useful!

All Github repos containing semver tags that start with `v` are available via gopkg.in. For example: https://gopkg.in/python/cpython.v3
