### ISSUE TITLE
Page.GetCookies returns an error

### ISSUE THREAD

**Issue by oinume** [sclevine/agouti#88]
Hi,

I found a problem that `Page.GetCookies` returns an error in some situation.
Source code of reproducing this problem is [here](https://gist.github.com/oinume/5621ffdb00d03ce0f1df71c34f645466).

```bash
$ go run main.go
2016/10/13 18:31:29 failed to get cookies: unexpected response: {"sessionId":"6047b1118716a455d5f17ab9172c9630","status":0,"value":[{"domain":"127.0.0.1","expiry":1476437485.974276,"httpOnly":true,"name":"test","path":"/","secure":false,"value":"test"}]}
exit status 1
```

I think the error is raised because `expiry` of the cookie is not integer.

**Comment by shift** [comment]
It looks like this PR https://github.com/sclevine/agouti/pull/71 would fix this issue.

**Comment by sclevine** [comment]
Merged, thanks for the report!

**Comment by oinume** [comment]
Thanks. It works!
