### ISSUE TITLE
sometime WebDriver.NewPage will be block on create a page

### ISSUE THREAD

**Issue by benzma** [sclevine/agouti#97]
page, err := driver.NewPage(agouti.Browser("firefox"), agouti.Timeout(1), agouti.Debug)

On code up. The timeout cann't effect. on file agouti/api/internal/bus/connect.go func openSession. The httpClient can not set timeout. I add code  httpClient.Timeout=30. on this func. it works.

so, how to set a good func to solve the timeout. It's due to you.

**Comment by sclevine** [comment]
You can use https://godoc.org/github.com/sclevine/agouti#HTTPClient to set the WebDriver connection timeout.
