### ISSUE TITLE
Selection.Exists() method?

### ISSUE THREAD

**Issue by jawnsy** [sclevine/agouti#99]
Hello,

What's the best way to determine if an element exists on a page? Two ways I've found are:

1. `page.Find("selection").Count()` > 0
2. `page.Find("selection").Visible()` is true

Both of these will return an error indicating that the selection isn't found; for example:

> failed to select elements from selection 'Link: "no such link" [single]': element not found

But if this is an expected case, I can't find any easy way to match on this type of error (other than a text match).

I'd like to add a new method (perhaps `Exists()`) which would return (bool, error), and would simply return false (without any error) if the element doesn't exist. Just opening this issue first for discussion, if it sounds sensible then I can create a PR.

Jonathan

**Comment by jawnsy** [comment]
Looks like this is doable by looking for a 404 status code: https://w3c.github.io/webdriver/webdriver-spec.html#dfn-no-such-element

**Comment by jawnsy** [comment]
Just found a [matcher that does this](https://github.com/sclevine/agouti/blob/master/matchers/internal/be_found.go#L21-L31), which looks for a string suffix - seems more reliable to have an error type or const that can be matched against, or to have a special Exists method as described.

**Comment by sclevine** [comment]
Use `page.All("selection").Count()`.

`page.Find` is for selecting exactly one element.

**Comment by jawnsy** [comment]
Hey Stephen,

Thanks for the quick reply! That method indeed doesn't return any errors if no matching elements are found. It makes sense that `Find` is for "exactly one match expected" and and `All` is for "zero or more"

It'd be nice to document this somewhere (and I'm happy to submit a PR to add those docs) but I'm not sure where the best place to put it would be?

Jonathan

**Comment by sclevine** [comment]
This is covered in the godoc:
https://godoc.org/github.com/sclevine/agouti#Selection.All
https://godoc.org/github.com/sclevine/agouti#MultiSelection.All
https://godoc.org/github.com/sclevine/agouti#Page.All

If you'd like to PR something more lengthy, the `gh-pages` branch of this repo backs agouti.org.
